// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0K0FQZR-1mCceS_kDZZUihc4UGMGNGIw',
    appId: '1:391834198658:web:c5bf4d694668d766598a9b',
    messagingSenderId: '391834198658',
    projectId: 'todo-app-flutter-8c53f',
    authDomain: 'todo-app-flutter-8c53f.firebaseapp.com',
    storageBucket: 'todo-app-flutter-8c53f.appspot.com',
    measurementId: 'G-1Z61LW0R27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS1UdLmDV55ix6WcNlIpmRPtGYMaqskJo',
    appId: '1:391834198658:android:8bb45ae77465ffa3598a9b',
    messagingSenderId: '391834198658',
    projectId: 'todo-app-flutter-8c53f',
    storageBucket: 'todo-app-flutter-8c53f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZWoNi9TVNIF0wXzF7TYkTVI1mxOXOAQU',
    appId: '1:391834198658:ios:6ae881d7422378ec598a9b',
    messagingSenderId: '391834198658',
    projectId: 'todo-app-flutter-8c53f',
    storageBucket: 'todo-app-flutter-8c53f.appspot.com',
    iosClientId: '391834198658-h4jtm553cp360i8p1jlb6ejsmctphfn0.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZWoNi9TVNIF0wXzF7TYkTVI1mxOXOAQU',
    appId: '1:391834198658:ios:6ae881d7422378ec598a9b',
    messagingSenderId: '391834198658',
    projectId: 'todo-app-flutter-8c53f',
    storageBucket: 'todo-app-flutter-8c53f.appspot.com',
    iosClientId: '391834198658-h4jtm553cp360i8p1jlb6ejsmctphfn0.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );
}
